### ISSUE TITLE
개발 도구 설정

### ISSUE THREAD

**Issue by pers0n4** [dnd-mentee-4th/dnd-mentee-4th-5-frontend#1]
## ESLint

- airbnb 룰 적용
  - 귀찮게 굴면 추후 airbnb를 날린다

## Prettier

- 2 space
- single quote

## Husky

- commit시 자동 formatting 및 linting 수행

## commitizen

- commitlint를 통한 강제 사항은 적용하지 않음

**Comment by sgd122** [comment]
expo 사용? 미사용?

**Comment by pers0n4** [comment]
> expo 사용? 미사용?

useExpo()
